name: CD

on:
  workflow_run:
    workflows: [""]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to deploy to your EC2 server here
      - name: Deploy to EC2
        run: |
          # Add any additional deployment steps here
          # Example: Copy configuration files, start services, etc.
