name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Java
      run: |
        echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
        echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
  
    - name: Build JAR using Maven
      run: |
        export MAVEN_HOME="C:\apache-maven-3.9.2"
        export PATH="$MAVEN_HOME/bin:$PATH"
        mvn clean package
      
    
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
    
    - name: Determine Docker image name and tag
      id: docker_info
      run: echo "::set-output name=image_name::ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}"
    
    - name: Build Docker image
      run: docker build -t ${{ steps.docker_info.outputs.image_name }}:latest .
    
    - name: Push Docker image to GitHub Container Registry
      run: docker push ${{ steps.docker_info.outputs.image_name }}:latest
