name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up Maven
          uses: actions/setup-java@v2
          with:
            java-version: 11
            maven-version: 3.8.4
            distribution: 'adopt'
            
        - name: Build with Maven
          run: mvn clean install
        
      
        - name: Build with Maven
          run: C:\apache-maven-3.9.2\bin\mvn clean install
  
        - name: Package the application
          run: |
            $outputPath = "javaapp.zip"
            $sourcePath = "C:\Users\c.bhavya\Desktop\cicd\java-application\target\java-app-1.0-SNAPSHOT.jar"
            Compress-Archive -Path $sourcePath -DestinationPath $outputPath
  
        - name: Set up Docker
          uses: docker/setup-qemu-action@v1

        - name: Create Dockerfile
          run: |
            echo "FROM openjdk:11" > Dockerfile
            echo "COPY javaapp.zip /app/" >> Dockerfile
            echo "WORKDIR /app" >> Dockerfile
            echo "RUN unzip javaapp.zip" >> Dockerfile
    
        - name: Build Docker image
          run: |
            docker build -t ghcr.io/${{ github.repository_owner }}/java-app:${{ github.sha }} .
          
        - name: Log in to GitHub Container Registry
          run: |
            echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
        - name: Push Docker image to GitHub Container Registry
          run: |
            docker push ghcr.io/${{ github.repository_owner }}/java-app:${{ github.sha }}
            
