name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/temurin-11" >> $GITHUB_ENV
        echo "PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

    - name: Set up Docker
      uses: docker/setup-docker@v1
      
    - name: Build Docker image
      run: |
        USERNAME="${{ github.repository_owner }}"
        REPO_NAME="${{ github.repository }}"
        IMAGE_TAG="${USERNAME}/${REPO_NAME}:${{ github.sha }}"
        docker build -f dockerfile -t ghcr.io/${IMAGE_TAG} .
      
    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin
      
    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/cbhavya09/cicd-python:${{ github.sha }}